# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('description', models.CharField(max_length=800)),
                ('is_blog_article', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=800)),
                ('preview_link', models.CharField(max_length=300)),
                ('full_link', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=300)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='person_site.Article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='metadatas',
            field=models.ManyToManyField(to='person_site.Metadata'),
        ),
        migrations.AddField(
            model_name='article',
            name='preview_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_site.Image'),
        ),
    ]
