# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_site', '0002_article_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
