# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_site', '0003_article_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='metadatas',
            field=models.ManyToManyField(null=True, to='person_site.Metadata'),
        ),
        migrations.AlterField(
            model_name='article',
            name='preview_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person_site.Image'),
        ),
    ]
