# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_site', '0004_auto_20170329_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='metadatas',
        ),
        migrations.AddField(
            model_name='article',
            name='message',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='message',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
